#!/bin/bash

# courtesy of http://web.archive.org/web/20200507173259/https://debian-administration.org/article/317/An_introduction_to_bash_completion_part_2
backlight-completion() 
{
    local cur prev opts colors
    COMPREPLY=()
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cur="${COMP_WORDS[COMP_CWORD]}"
    colors="white silver gray yellow orange red maroon crimson fuchsia purple rose cyan turquoise teal blue navy olive lime green"
    opts="ui off breathe brightness cycle dance flash color random tempo wave -h --help"


    if [[ ${prev} == "color" ]] ; then
        COMPREPLY=( $(compgen -W "${colors}" ${cur}) )
        return 0
    elif [[ ${prev} == "backlight" ]] ; then
        COMPREPLY=( $(compgen -W "${opts}" ${cur}) )
        return 0
    fi
}
complete -F backlight-completion backlight